### ISSUE TITLE
Members not listed

### ISSUE THREAD

**Issue by Duckster73** [robertjf/umbMemberListView#9]
Following an upgrade from Umbraco 7.10 to 7.15.1, and with package 1.2.0, the list of members is now showing completely empty.  (Also tested with package 1.3.0 with the same result)

I am able to search for the Members in the Developer section, and the results include the __Key

Log error shows:

```
2019-08-07 17:52:29,044 [P15200/D10/T249] ERROR MemberListView.Controllers.MemberApiController - Unhandled controller exception occurred
System.Web.Http.HttpResponseException: Processing of the HTTP request resulted in an exception. Please see the HTTP response returned by the 'Response' property of this exception for details.
   at System.Web.Http.ModelBinding.FormatterParameterBinding.ReadContentAsync(HttpRequestMessage request, Type type, IEnumerable`1 formatters, IFormatterLogger formatterLogger, CancellationToken cancellationToken)
   at System.Web.Http.ModelBinding.FormatterParameterBinding.ReadContentAsync(HttpRequestMessage request, Type type, IEnumerable`1 formatters, IFormatterLogger formatterLogger)
   at System.Web.Http.ModelBinding.FormatterParameterBinding.<ExecuteBindingAsyncCore>d__18.MoveNext()
```
In Browser Developer Tools window open on the Network tab, it's throwing some 415 errors, with the response: "The request contains an entity body but no Content-Type header. The inferred media type 'application/octet-stream' is not supported for this resource."

**Comment by Duckster73** [comment]
See also:  https://our.umbraco.com/packages/backoffice-extensions/memberlistview-for-umbraco-7/say-hello/94338-memberlistview-no-results

**Comment by robertjf** [comment]
@Duckster73 the latest update now supports Umbraco 7.15.1+ and includes some new features.

Sorry about the delay, unfortunately until recently we've not had the bandwidth to do anything about it.
